### ISSUE TITLE
Verify instructions channel

### ISSUE THREAD

**Issue by TFJ1802** [skyron-Cloud/Verifie-Issue-Tracker#2]
This would be a channel where the bot prints text in a nice embed. The text would say something like: Hello, you may have noticed that there is not many channels you can see, this is because this server enforces user verification. To enter the server and see all the channels please use the bot command `!verify`.

You could do this yourself but I think this would look nicer on the whole.

**Comment by HarriHK** [comment]
So, you mean a category where the instructions and #verify are created by the bot? Soon.

**Comment by TFJ1802** [comment]
Well yes possibly, but the main thing is the bot prints an embed in a specified channel, whether it could be done as part of a setup command I don't know.

**Comment by HarriHK** [comment]
Sure

**Comment by TFJ1802** [comment]
Amazing.
