### ISSUE TITLE
Custom Tick and Cross emojis.

### ISSUE THREAD

**Issue by TFJ1802** [skyron-Cloud/Verifie-Issue-Tracker#3]
I think this would be a nice feature since I am not a fan of discord white cross and tick emojis, would be great if they were replaced with custom ones that were uploaded to your server, E.G `-setemoji cross :no:` This would be used in the reaction part of the verification prosses (Roblox.)

Its not a essential but it would be nice to have.

**Comment by Bfo2123** [comment]
I am not sure if it would work with server emojis. (Especially Nitro ones)

**Comment by TFJ1802** [comment]
Not animated, just the in server ones, would not need nitro.

**Comment by HarriHK** [comment]
Database can't save emojis so It won't work
